triggers:
- envs: []
  last_enabled_at: 2024-02-13 19:38:37.895127
  name: daily_bronze_etl_sf_fi
  pipeline_uuid: bronze_etl_sf_f1
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-02-13 07:00:00
  status: active
  variables: {}
